-- ============================================================
-- Booking System — D1 Schema
-- Run via: wrangler d1 execute booking-db --file=schema/001_init.sql
-- ============================================================

-- Slots: the availability you configure as admin
CREATE TABLE IF NOT EXISTS slots (
  id          TEXT PRIMARY KEY,           -- e.g. "2025-06-10T10:00"
  date        TEXT NOT NULL,              -- "2025-06-10"
  time        TEXT NOT NULL,              -- "10:00"
  label       TEXT NOT NULL,              -- "10:00 AM" (display)
  price_pence INTEGER NOT NULL,           -- price in pence/cents (avoid floats)
  currency    TEXT NOT NULL DEFAULT 'gbp',
  is_active   INTEGER NOT NULL DEFAULT 1, -- 1=bookable, 0=hidden
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Bookings: created only after Stripe confirms payment
CREATE TABLE IF NOT EXISTS bookings (
  id                TEXT PRIMARY KEY,     -- UUID generated by worker
  slot_id           TEXT NOT NULL REFERENCES slots(id),
  client_name       TEXT NOT NULL,
  client_email      TEXT NOT NULL,
  stripe_session_id TEXT UNIQUE NOT NULL,
  stripe_payment_id TEXT,
  amount_paid_pence INTEGER NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'gbp',
  status            TEXT NOT NULL DEFAULT 'pending',
  -- status values: pending | confirmed | cancelled
  cancel_note       TEXT,
  created_at        TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at        TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Index for fast availability lookups
CREATE INDEX IF NOT EXISTS idx_slots_date     ON slots(date);
CREATE INDEX IF NOT EXISTS idx_bookings_slot  ON bookings(slot_id);
CREATE INDEX IF NOT EXISTS idx_bookings_email ON bookings(client_email);
CREATE INDEX IF NOT EXISTS idx_bookings_stripe ON bookings(stripe_session_id);
